# Generated by Django 3.2.7 on 2021-11-23 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_task_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
